---
title: "EDS 221 Day 2 Interactive Lessons"
format: html
editor: visual
execute: 
  warning: FALSE
---

```{r}
library(tidyverse)
```

## Making and indexing data in R

### Vectors

Making vectors

```{r}
dogs <- c("teddy", "khora", "waffle", "banjo", "tallie")

# Check class of dogs
typeof(dogs)
class(dogs)
```

```{r}
my_breakfast <- c("waffles", 2, TRUE, "coffee")

typeof(my_breakfast) # entire vector becomes character
```

```{r}
weights <- c(50, 60, 25, 35, 55)

typeof(weights)
class(weights)
```

```{r}
weights_integer <- c(50L, 60L, 25L, 35L, 55L)

typeof(weights_integer)
class(weights_integer)
```

```{r}
# is. asks a question -- ask what class something is
is.numeric(weights_integer)
```

```{r}
zipcodes <- c(93105, 93514, 93101, 93401)

class(zipcodes)

# as. gives instructions, use to recast data classes
zipcodes_chr <- as.character(zipcodes)

class(zipcodes_chr)
```

### Create a vector with named elements

```{r}
dog_food <- c(teddy = "purina", khora = "alpo", waffle = "fancy feast", banjo = "blue diamond", tallie = "farmer's dog")

tes <- c(cat = 4, dog = 10, elephant = 11)
```

```{r}
dog_food[2]
# R uses a 1-index
# Python and JavaScript use 0-indexing
```

```{r}
dog_food["khora"]
```

Access ranges of values in a vector

Use : to refer to a range (low : high)

```{r}
trees <- c("ponderosa", "lodgepole", "jeffrey", "sugar", "white", "bristlecone")

trees[3]

trees[3:5]
```

## Warm up for for loops

```{r}
i <- 3
trees[i]
```

```{r}
i <- seq(1:3) # same as writing seq(from = 1, to = 3)
trees[i]
```

```{r}
# can reassign values based on the position
trees[3] <- "oak"
trees
```

## Matrix indexing

```{r}
fish_size <- matrix(c(0.8, 1.2, 0.4, 0.9), ncol = 2, nrow = 2, byrow = FALSE)

fish_size

class(fish_size)
str(fish_size)
typeof(fish_size)

fish_size[2,2]

fish_size[, 2]
```

An edit!

## Lists

```{r}
urchins <- list(color = "blue", values = c(1, 2, 3), meal = c("lunch", "dinner", "dessert"), cost = 5L)
```

```{r}
urchins_list <- urchins[2]

urchins_vector <- urchins[[2]]

```

```{r}
urchins$values
```

```{r}
sample1 <- c(1,2,3,4,5,6,3,2,5)
sample2 <- c(2,3,4,5,3,2,9,10)

ttest_ex <- t.test(sample1, sample2)
```

## Data frames

```{r}
fruit <- data.frame(type = c("apple", "banana", "peach"),
                    mass = c(130, 195, 150))

fruit

fruit[3, 2]

purrr::pluck(fruit, "type", 2) # more readable and linear way to index

starwars$starships[[1]][2] # [[]] gives us the values, NOT as a list
purrr::pluck(starwars, "starships", 1, 2) # gives same output, but easier to read, etc.
```
